# Generated by Django 5.1.7 on 2025-03-14 06:18

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('manifest_register_number', models.IntegerField()),
                ('sender_name', models.CharField(max_length=255)),
                ('send_date', models.DateField()),
                ('total_products', models.IntegerField()),
                ('total_recipients', models.IntegerField()),
                ('total_weight', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
                'ordering': ['-send_date', 'sender_name'],
            },
        ),
        migrations.CreateModel(
            name='ExcelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Excel документ',
                'verbose_name_plural': 'Excel документы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_id', models.CharField(max_length=255)),
                ('invoice', models.CharField(max_length=255)),
                ('awb', models.CharField(max_length=255)),
                ('sticker', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('netto', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('brutto', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('tn_ved', models.CharField(max_length=255)),
                ('shk', models.CharField(max_length=255)),
                ('recipient_fullname', models.CharField(max_length=255)),
                ('recipient_passport', models.CharField(max_length=7)),
                ('recipient_pinfl', models.CharField(max_length=14)),
                ('recipient_birthdate', models.CharField(max_length=10)),
                ('recipient_country_code', models.CharField(max_length=2)),
                ('recipient_city_name', models.CharField(max_length=255)),
                ('recipient_address', models.CharField(max_length=255)),
                ('recipient_phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('box_number', models.CharField(max_length=255)),
                ('delivery_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_main.deliverybatch')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
