# Generated by Django 5.1.7 on 2025-03-14 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.deliverybatch'),
        ),
    ]
