# Generated by Django 5.1.7 on 2025-03-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_exceldocument_alter_deliverybatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverybatch',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
