# Generated by Django 5.1.7 on 2025-03-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_alter_product_delivery_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sender', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=1)),
                ('what_is_inside', models.CharField(max_length=3)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=50)),
                ('additional_percent', models.DecimalField(decimal_places=1, max_digits=12)),
                ('final_price', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='SupplierExcelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Excel документ поставщика',
                'verbose_name_plural': 'Excel документы поставщиков',
            },
        ),
    ]
