# Generated by Django 5.1.7 on 2025-03-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_supplier_supplierexceldocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldocument',
            name='document',
            field=models.FileField(upload_to='documents/products/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='additional_percent',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='supplierexceldocument',
            name='document',
            field=models.FileField(upload_to='documents/suppliers/'),
        ),
    ]
