# Generated by Django 5.1.7 on 2025-03-11 16:59

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_deliverybatch_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exceldocument',
            options={'verbose_name': 'Excel документ', 'verbose_name_plural': 'Excel документы'},
        ),
        migrations.AlterField(
            model_name='deliverybatch',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('invoice', models.CharField(max_length=255)),
                ('awb', models.CharField(max_length=255)),
                ('sticker', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('netto', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('brutto', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('tn_ved', models.CharField(max_length=255)),
                ('shk', models.CharField(max_length=255)),
                ('recipient_fullname', models.CharField(max_length=255)),
                ('recipient_passport', models.CharField(max_length=7)),
                ('recipient_pinfl', models.CharField(max_length=14)),
                ('recipient_birthdate', models.DateField()),
                ('recipient_country_code', models.CharField(max_length=2)),
                ('recipient_city_name', models.CharField(max_length=255)),
                ('recipient_address', models.CharField(max_length=255)),
                ('recipient_phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('box_number', models.CharField(max_length=255)),
                ('delivery_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_main.deliverybatch')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
