# Generated by Django 5.1.7 on 2025-03-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_alter_exceldocument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recipient_birthdate',
            field=models.DateField(null=True),
        ),
    ]
