# Generated by Django 5.1.7 on 2025-03-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_alter_product_recipient_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recipient_birthdate',
            field=models.CharField(max_length=10),
        ),
    ]
